name: Deploy React App to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the app
      run: |
        npm run build

    - name: Deploy to Firebase Hosting
      run: |
        curl -sL https://firebase.tools | bash
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
        REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
